"""empty message

Revision ID: 2f06a3b9c14b
Revises: 
Create Date: 2025-02-13 12:02:18.009942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f06a3b9c14b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Matches',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UUID', sa.String(length=50), nullable=False),
    sa.Column('Player1', sa.Integer(), nullable=False),
    sa.Column('Player2', sa.Integer(), nullable=False),
    sa.Column('Winner', sa.Integer(), nullable=True),
    sa.Column('Score', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Player1'], ['Players.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Player2'], ['Players.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Winner'], ['Players.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UUID')
    )
    op.drop_index('UUID', table_name='matches')
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('matches',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UUID', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Player1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Player2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Winner', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Score', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Player1'], ['players.ID'], name='matches_ibfk_1'),
    sa.ForeignKeyConstraint(['Player2'], ['players.ID'], name='matches_ibfk_2'),
    sa.ForeignKeyConstraint(['Winner'], ['players.ID'], name='matches_ibfk_3'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UUID', 'matches', ['UUID'], unique=True)
    op.drop_table('Matches')
    op.drop_table('Players')
    # ### end Alembic commands ###
